/*

 LIFE_BKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\gbtd\life_tile_set.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define life_bkgWidth 20
#define life_bkgHeight 18
#define life_bkgBank 0

extern unsigned char life_bkg[];

/* End of LIFE_BKG.H */
